[package]
name = "qmlbind20"
version = "0.1.0"
authors = ["whs31 <whs31@github.io>"]
description = "C++ to QML bindings inspired by pybind11"

[dependencies]
cmake = { version = "0.1.2", distribution = "sources" }
leaf = { version = "0.4.1", distribution = "static" }