[package]
name = "leaf"
authors = ["whs31 <whs31@github.io>"]
description = "Core library of simulator namespace and beyond"

[package.version]
major = 0
minor = 3
patch = 4

[dependencies]
cmake = { version = { major = 0, minor = 1, patch = 2 }, distribution = "sources" }
fmt = { version = { major = 10, minor = 1, patch = 1 }, distribution = "static" }
spdlog = { version = { major = 1, minor = 13, patch = 0 }, distribution = "static" }