[this]
name = "qmlbind20"
version = "0.1.0"
authors = [
    "whs31 <whs31@github.io>"
]
description = "C++ to QML bindings inspired by pybind11"

[needs]
cmake = "^0.1.3@static"
leaf = "^0.4.1@static"