name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "http://uav.radar-mms.com/gitlab/test/essentials/qmlbind20"
      env:
        FOLLOW_TAGS: "false"
        FORCE_PUSH: "false"
        GITLAB_HOSTNAME: "uav.radar-mms.com/gitlab"
        GITLAB_USERNAME: "ryazancev_dl"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }} 
        GITLAB_PROJECT_ID: "451" 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 